name: Build Custom ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib \
          git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
          lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev \
          libssl-dev libxml2 libxml2-utils lzop pngcrush \
          rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
          openjdk-11-jdk repo
          
    - name: Initialize ROM repo
      run: |
        mkdir rom && cd rom
        repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
        repo sync -j$(nproc) --force-sync

    - name: Clone device tree
      run: |
        cd rom
        git clone https://github.com/your-username/device_xxx_xxx -b your-branch device/brand/device
        git clone https://github.com/your-username/vendor_xxx_xxx -b your-branch vendor/brand/device
        git clone https://github.com/your-username/kernel_xxx_xxx -b your-branch kernel/brand/device

    - name: Start build
      run: |
        cd rom
        source build/envsetup.sh
        lunch lineage_device-userdebug
        mka bacon -j$(nproc)
