name: Build GSI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk bc bison build-essential curl \
          flex g++-multilib gcc-multilib git gnupg gperf imagemagick \
          lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool \
          libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
          lzop pngcrush rsync schedtool squashfs-tools xsltproc zip \
          zlib1g-dev repo git wget ccache

    - name: Initialize AOSP repo
      run: |
        mkdir aosp && cd aosp
        repo init -u https://android.googlesource.com/platform/manifest -b android-13.0.0_r30
        repo sync -c -j$(nproc) --force-sync

    - name: Clone GSI build tools
      run: |
        cd aosp
        git clone https://github.com/phhusson/treble_experimentations -b android-13.0

    - name: Build GSI (64-bit AB)
      run: |
        cd aosp
        bash treble_experimentations/build-dakkar.sh 64 ab

    - name: Upload GSI
      uses: actions/upload-artifact@v4
      with:
        name: GSI
        path: aosp/out/target/product/*/*.img
